{{- if and .Values.persistentVolume.enabled (not (eq .Values.kind "StatefulSet")) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "template.fullname" . }}
  labels:
    {{- include "template.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.persistentVolume.storageClassName | default ""}}
  accessModes:
    {{- toYaml .Values.persistentVolume.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistentVolume.capacity }}
  persistentVolumeMode: {{ .Values.persistentVolume.mode }}
{{- end }}